# Generated by Django 4.2.1 on 2023-05-23 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employment_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Previous_CompanyName', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Date_of_Employment', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
                ('Present_Address', models.CharField(max_length=100)),
                ('Achievements', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Father_Name', models.CharField(max_length=100)),
                ('Mother_Name', models.CharField(max_length=100)),
                ('Contact_Number', models.CharField(max_length=13)),
                ('Emergency_Number', models.CharField(max_length=10)),
                ('Present_Address', models.CharField(max_length=100)),
                ('Permanent_Address', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salary_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=13)),
                ('Dob', models.DateField()),
                ('Blood_Group', models.CharField(max_length=25)),
                ('employee_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.personal_details')),
            ],
        ),
    ]
